version: '3.8'

services:
  payment-postgres:
    image: bitnami/postgresql:latest
    container_name: payment-postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=payment
    volumes:
      - payment_pg_data:/bitnami/postgresql
    networks:
      - pgcloudbeaver-network-external

  pgadmin-docker:
    image: dpage/pgadmin4
    container_name: dev-pgadmin
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - payment_pgAdmin_data:/var/lib/pgadmin
    depends_on:
      - payment-postgres  # Aqui, altere para o novo nome do serviço
    networks:
      - pgcloudbeaver-network-external

volumes:
  payment_pg_data:
  payment_pgAdmin_data:

networks:
  pgcloudbeaver-network-external:
    driver: bridge
